;===============================================================
; SAMPLE CONFIG FILE
; Copy this file to "config.ini" and fill values manually.
;===============================================================

;---------------------------------------------------------------
; Database configuration
;---------------------------------------------------------------
[DATABASE]
host = 'localhost'
name = 'my_database'
user = 'db_user'
password = 'db_password'



;---------------------------------------------------------------
; MAIL configuration
;---------------------------------------------------------------
[MAIL]
; Choose which provider to use:
;   "google" = Gmail (requires app password)
;   "smtp"   = Standard SMTP server (Hostinger, OVH, IUT, etc.)
provider = "smtp"


;---------------------------------------------------------------
; Google SMTP configuration
; Used ONLY if provider = "google"
;---------------------------------------------------------------
[GOOGLE_SMTP]
user = "example@gmail.com"
from_name = 'My Application - No Reply'
password = "google-app-password"


;---------------------------------------------------------------
; Generic SMTP configuration
; Used ONLY if provider = "smtp"
;---------------------------------------------------------------
[SMTP]
host = "smtp.example.com"
port = 587
auth = true
user = "noreply@example.com"
password = "smtp_password"
encryption = "tls" ; encryption can be: "tls" / "ssl" / "none"
from_email = "noreply@example.com"
from_name = "My Application - No Reply"